"""Deterministic extraction primitives. Later stages build pipeline steps from these."""

from __future__ import annotations

from intelligence.extraction.boilerplate import (
    BOILERPLATE_SEMANTICS,
    Boilerplate,
    BodySplit,
    body_without_stamps,
    drop_ranges,
    find_boilerplate,
    split as split_boilerplate,
)
from intelligence.extraction.language import (
    DOMINANT_SCRIPT_RATIO,
    ENGLISH_FUNCTION_WORDS,
    PRESENT_SCRIPT_RATIO,
    ScriptProfile,
    assess,
    detection,
    english_vocabulary_found,
    hint_conflict,
    language_info,
    normalise_hint,
    profile,
    representation_id,
    script_bucket,
    source_representation,
)
from intelligence.extraction.morphology import (
    MIN_STEM_LENGTH,
    SUFFIX_RULES,
    MorphologyError,
    SuffixCandidate,
    analyze_tokens,
    matches_surface,
    suffix_candidates,
    surface_forms,
    tokenize,
)
from intelligence.extraction.normalize import (
    MappedText,
    MappingError,
    build_mapped_text,
    cluster_end,
    normalize,
    normalize_field,
)
from intelligence.extraction.spans import (
    AmbiguousQuoteError,
    EmptyQuoteError,
    OccurrenceOutOfBoundsError,
    PROBABILISTIC_METHODS,
    QuoteNotFoundError,
    Span,
    SpanCheck,
    SpanError,
    SourceField,
    build_evidence,
    build_evidence_at,
    build_metadata_evidence,
    compute_field_hash,
    derive_evidence_id,
    derive_metadata_evidence_id,
    find_spans,
    locate,
    revalidate,
    verify_evidence,
)
from intelligence.extraction.temporal import (
    STAMP_SEMANTICS,
    TemporalError,
    TemporalExtraction,
    TemporalMention,
    extract as extract_temporal,
    unresolved_time,
)
from intelligence.extraction.time_expressions import (
    Expression as TemporalExpression,
    KINDS as TEMPORAL_KINDS,
    Resolution as TemporalResolution,
    find as find_time_expressions,
    reporting_cue,
    resolve as resolve_time_expression,
    timezone_cue,
)
from intelligence.extraction.transliteration import (
    VOCABULARY,
    TransliterationCandidate,
    candidates as transliteration_candidates,
    candidates_for_text,
    render_cluster,
    transliterate,
    transliterated_field,
    vocabulary_term,
)
from intelligence.extraction.transliteration import representation as transliterated_representation

__all__ = [
    "BOILERPLATE_SEMANTICS",
    "DOMINANT_SCRIPT_RATIO",
    "ENGLISH_FUNCTION_WORDS",
    "MIN_STEM_LENGTH",
    "PRESENT_SCRIPT_RATIO",
    "PROBABILISTIC_METHODS",
    "SUFFIX_RULES",
    "STAMP_SEMANTICS",
    "TEMPORAL_KINDS",
    "AmbiguousQuoteError",
    "Boilerplate",
    "BodySplit",
    "EmptyQuoteError",
    "MappedText",
    "MappingError",
    "MorphologyError",
    "OccurrenceOutOfBoundsError",
    "QuoteNotFoundError",
    "ScriptProfile",
    "SourceField",
    "Span",
    "SpanCheck",
    "SpanError",
    "SuffixCandidate",
    "TemporalError",
    "TemporalExpression",
    "TemporalExtraction",
    "TemporalMention",
    "TemporalResolution",
    "TransliterationCandidate",
    "VOCABULARY",
    "analyze_tokens",
    "assess",
    "body_without_stamps",
    "build_evidence",
    "build_evidence_at",
    "build_mapped_text",
    "build_metadata_evidence",
    "cluster_end",
    "candidates_for_text",
    "compute_field_hash",
    "derive_evidence_id",
    "derive_metadata_evidence_id",
    "detection",
    "drop_ranges",
    "english_vocabulary_found",
    "extract_temporal",
    "find_boilerplate",
    "find_spans",
    "find_time_expressions",
    "hint_conflict",
    "language_info",
    "locate",
    "matches_surface",
    "normalize",
    "normalize_field",
    "normalise_hint",
    "profile",
    "render_cluster",
    "reporting_cue",
    "resolve_time_expression",
    "revalidate",
    "source_representation",
    "representation_id",
    "script_bucket",
    "split_boilerplate",
    "suffix_candidates",
    "surface_forms",
    "timezone_cue",
    "tokenize",
    "transliteration_candidates",
    "transliterated_field",
    "transliterated_representation",
    "transliterate",
    "unresolved_time",
    "verify_evidence",
    "vocabulary_term",
]
