"""Deterministic extraction primitives. Later stages build pipeline steps from these."""

from __future__ import annotations

from intelligence.extraction.actors import (
    ActorError,
    ActorExtraction,
    ActorMention,
    ActorOccurrence,
    ActorRefusal,
    Cue as ActorCue,
    Entity as ActorEntity,
    extract as extract_actors,
    find_entities as find_actor_entities,
)
from intelligence.extraction.boilerplate import (
    BOILERPLATE_SEMANTICS,
    Boilerplate,
    BodySplit,
    body_without_stamps,
    drop_ranges,
    find_boilerplate,
    split as split_boilerplate,
)
from intelligence.extraction.cues import (
    CueExtraction,
    CueFinding,
    CueMatch,
    NonEventMatch,
    Refusal as CueRefusal,
    find_cues,
    extract as extract_cues,
)
from intelligence.extraction.correlation import (
    DEDUP_ALGORITHM_VERSION,
    DISTRICT_LEVEL,
    IncidentProfile,
    PairReading,
    PairSignals,
    build_cluster,
    canonical_of,
    compare_profiles,
    merge_groups,
    page_of,
    profile_groups,
    read_pair,
    text_fingerprint,
    time_signal,
    token_signature,
    type_conflicts,
)
from intelligence.extraction.event_classification import (
    CANDIDATE_FLOOR,
    RESOLVE_FLOOR,
    TIE_MARGIN,
    Anchor,
    TypeScore,
    anchor_of,
    decide_event_type,
    decide_relevance,
    department_hints,
    score_types,
)
from intelligence.extraction.language import (
    DOMINANT_SCRIPT_RATIO,
    ENGLISH_FUNCTION_WORDS,
    PRESENT_SCRIPT_RATIO,
    ScriptProfile,
    assess,
    detection,
    english_vocabulary_found,
    hint_conflict,
    language_info,
    normalise_hint,
    profile,
    representation_id,
    script_bucket,
    source_representation,
)
from intelligence.extraction.mention_text import (
    Candidate as StemCandidate,
    Entry as LexiconEntry,
    Lexicon,
    Match as LexiconMatch,
    MentionTextError,
    Prose,
    Word,
    blocked,
    build_prose,
    fold as fold_surface,
    not_an_entity,
    read_word,
    stem_candidates,
)
from intelligence.extraction.morphology import (
    MIN_STEM_LENGTH,
    SUFFIX_RULES,
    MorphologyError,
    SuffixCandidate,
    analyze_tokens,
    matches_surface,
    suffix_candidates,
    surface_forms,
    tokenize,
)
from intelligence.extraction.normalize import (
    MappedText,
    MappingError,
    build_mapped_text,
    cluster_end,
    normalize,
    normalize_field,
)
from intelligence.extraction.place_expressions import (
    PlaceExpression,
    PlaceFinding,
    PlaceReadingError,
    Rejection as PlaceRejection,
    find as find_place_expressions,
)
from intelligence.extraction.places import (
    DistrictText,
    Occurrence as PlaceOccurrence,
    PlaceError,
    PlaceExtraction,
    PlaceMention,
    apply as apply_places,
    extract as extract_places,
)
from intelligence.extraction.spans import (
    AmbiguousQuoteError,
    EmptyQuoteError,
    OccurrenceOutOfBoundsError,
    PROBABILISTIC_METHODS,
    QuoteNotFoundError,
    Span,
    SpanCheck,
    SpanError,
    SourceField,
    build_evidence,
    build_evidence_at,
    build_metadata_evidence,
    compute_field_hash,
    derive_evidence_id,
    derive_metadata_evidence_id,
    find_spans,
    locate,
    revalidate,
    verify_evidence,
)
from intelligence.extraction.temporal import (
    STAMP_SEMANTICS,
    TemporalError,
    TemporalExtraction,
    TemporalMention,
    extract as extract_temporal,
    unresolved_time,
)
from intelligence.extraction.time_expressions import (
    Expression as TemporalExpression,
    KINDS as TEMPORAL_KINDS,
    Resolution as TemporalResolution,
    find as find_time_expressions,
    reporting_cue,
    resolve as resolve_time_expression,
    timezone_cue,
)
from intelligence.extraction.transliteration import (
    VOCABULARY,
    TransliterationCandidate,
    candidates as transliteration_candidates,
    candidates_for_text,
    render_cluster,
    transliterate,
    transliterated_field,
    vocabulary_term,
)
from intelligence.extraction.transliteration import representation as transliterated_representation

__all__ = [
    "BOILERPLATE_SEMANTICS",
    "CANDIDATE_FLOOR",
    "DEDUP_ALGORITHM_VERSION",
    "DISTRICT_LEVEL",
    "DOMINANT_SCRIPT_RATIO",
    "ENGLISH_FUNCTION_WORDS",
    "MIN_STEM_LENGTH",
    "RESOLVE_FLOOR",
    "PRESENT_SCRIPT_RATIO",
    "PROBABILISTIC_METHODS",
    "SUFFIX_RULES",
    "STAMP_SEMANTICS",
    "TEMPORAL_KINDS",
    "TIE_MARGIN",
    "VOCABULARY",
    "ActorCue",
    "ActorEntity",
    "ActorError",
    "ActorExtraction",
    "ActorMention",
    "ActorOccurrence",
    "ActorRefusal",
    "AmbiguousQuoteError",
    "Anchor",
    "CueExtraction",
    "CueFinding",
    "CueMatch",
    "CueRefusal",
    "Boilerplate",
    "BodySplit",
    "DistrictText",
    "EmptyQuoteError",
    "IncidentProfile",
    "Lexicon",
    "LexiconEntry",
    "LexiconMatch",
    "MappedText",
    "MappingError",
    "MentionTextError",
    "MorphologyError",
    "NonEventMatch",
    "OccurrenceOutOfBoundsError",
    "PairReading",
    "PairSignals",
    "PlaceError",
    "PlaceExtraction",
    "PlaceExpression",
    "PlaceFinding",
    "PlaceMention",
    "PlaceOccurrence",
    "PlaceReadingError",
    "PlaceRejection",
    "Prose",
    "QuoteNotFoundError",
    "ScriptProfile",
    "SourceField",
    "Span",
    "SpanCheck",
    "SpanError",
    "StemCandidate",
    "SuffixCandidate",
    "TemporalError",
    "TemporalExpression",
    "TemporalExtraction",
    "TemporalMention",
    "TemporalResolution",
    "TransliterationCandidate",
    "TypeScore",
    "Word",
    "analyze_tokens",
    "anchor_of",
    "apply_places",
    "assess",
    "blocked",
    "body_without_stamps",
    "build_evidence",
    "build_evidence_at",
    "build_mapped_text",
    "build_metadata_evidence",
    "build_prose",
    "build_cluster",
    "canonical_of",
    "candidates_for_text",
    "cluster_end",
    "compare_profiles",
    "decide_event_type",
    "decide_relevance",
    "department_hints",
    "compute_field_hash",
    "derive_evidence_id",
    "derive_metadata_evidence_id",
    "detection",
    "drop_ranges",
    "english_vocabulary_found",
    "extract_actors",
    "extract_cues",
    "extract_places",
    "extract_temporal",
    "find_actor_entities",
    "find_boilerplate",
    "find_cues",
    "find_place_expressions",
    "find_spans",
    "find_time_expressions",
    "fold_surface",
    "hint_conflict",
    "language_info",
    "locate",
    "matches_surface",
    "merge_groups",
    "normalize",
    "normalize_field",
    "normalise_hint",
    "not_an_entity",
    "page_of",
    "profile",
    "profile_groups",
    "read_pair",
    "read_word",
    "render_cluster",
    "reporting_cue",
    "resolve_time_expression",
    "score_types",
    "revalidate",
    "source_representation",
    "representation_id",
    "script_bucket",
    "split_boilerplate",
    "stem_candidates",
    "suffix_candidates",
    "surface_forms",
    "text_fingerprint",
    "time_signal",
    "token_signature",
    "timezone_cue",
    "tokenize",
    "type_conflicts",
    "transliteration_candidates",
    "transliterated_field",
    "transliterated_representation",
    "transliterate",
    "unresolved_time",
    "verify_evidence",
    "vocabulary_term",
]
