"""The record seam: CommonRecord-shaped input to Stage 1 Incident output."""

from __future__ import annotations

from intelligence.mapping.assembly import (
    DEFAULT_TIMEZONE,
    PROVIDER,
    STAGE_VERSIONS,
    IncidentDraft,
    MappingPolicy,
    derive_incident_id,
    map_record,
    time_precision_of,
    unresolved_field_count,
    verify_draft,
)
from intelligence.mapping.enrichment import (
    enrich_incident,
    find_actors,
    find_places,
    read_prose,
)
from intelligence.mapping.feed_policies import (
    AGRICULTURE,
    DEFAULT,
    FEED_POLICIES,
    NEWS,
    WEATHER,
    policy_for,
)
from intelligence.mapping.classifier import (
    CLASSIFICATION_SECTION,
    RELEVANCE_SECTION,
    classify_incident,
    read_cues,
)
from intelligence.mapping.deduplication import (
    DEDUP_SECTION,
    MERGING,
    CorrelationResult,
    candidate_pairs,
    correlate_incidents,
    profile_of,
    record_signature,
)
from intelligence.mapping.record_input import (
    CONTENT_PATH,
    DISTRICT_PATH,
    EVENT_TIME_PATH,
    IDENTITY_PATHS,
    LANGUAGE_PATH,
    RETRIEVED_AT_PATH,
    TITLE_PATH,
    CommonRecordLike,
    MappingError,
    RecordInput,
    RecordShapeError,
    UnreadableRecord,
    input_hash,
    read_record,
)

__all__ = [
    "AGRICULTURE",
    "CLASSIFICATION_SECTION",
    "CONTENT_PATH",
    "CommonRecordLike",
    "DEDUP_SECTION",
    "DEFAULT",
    "FEED_POLICIES",
    "DEFAULT_TIMEZONE",
    "DISTRICT_PATH",
    "EVENT_TIME_PATH",
    "IDENTITY_PATHS",
    "LANGUAGE_PATH",
    "MERGING",
    "MappingError",
    "MappingPolicy",
    "NEWS",
    "PROVIDER",
    "RETRIEVED_AT_PATH",
    "RecordInput",
    "RecordShapeError",
    "RELEVANCE_SECTION",
    "STAGE_VERSIONS",
    "TITLE_PATH",
    "WEATHER",
    "CorrelationResult",
    "IncidentDraft",
    "UnreadableRecord",
    "candidate_pairs",
    "classify_incident",
    "correlate_incidents",
    "derive_incident_id",
    "enrich_incident",
    "find_actors",
    "find_places",
    "input_hash",
    "map_record",
    "policy_for",
    "profile_of",
    "read_cues",
    "read_prose",
    "read_record",
    "record_signature",
    "time_precision_of",
    "unresolved_field_count",
    "verify_draft",
]
